/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_projectakshara_android_finman_OpenCVActivity */

#ifndef _Included_org_projectakshara_android_finman_OpenCVActivity
#define _Included_org_projectakshara_android_finman_OpenCVActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_projectakshara_android_finman_OpenCVActivity
 * Method:    processBill
 * Signature: (Lorg/projectakshara/android/finman/Bill;Ljava/lang/String;)I
 */
// jobject,
JNIEXPORT jint JNICALL Java_org_projectakshara_android_finman_OpenCVActivity_processBill
  (JNIEnv *,jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
